# Generated by Django 5.1.2 on 2024-10-21 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0002_alter_buyer_balance_alter_game_cost_alter_game_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='description',
            field=models.TextField(default='Простые игры'),
            preserve_default=False,
        ),
    ]
